Repository openebs/zfs-localpv, pull requests merged in 2020-03, with the labels that each got.

#65 chore(readme): adding e2e project link in README
  README.md
Labels: documentation

#64 fix(xfs): clearing the xfs log before generating UUID
  pkg/zfs/xfs_util.go
  pkg/zfs/zfs_util.go
Labels: bug

#71 fix(test): fixing resize flaky test case
  ci/ci-test.sh
  tests/suite_test.go
  tests/utils.go
Labels: bug

#68 Upgrade the base ubuntu package for ZFS plugin
  buildscripts/zfs-driver/Dockerfile
Labels: bug

#70 feat(crd): refactoring CRD
  Makefile
  ci/ci-test.sh
  deploy/zfs-operator.yaml
  pkg/apis/openebs.io/zfs/v1alpha1/doc.go
  pkg/apis/openebs.io/zfs/v1alpha1/register.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfssnapshot.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
  pkg/apis/openebs.io/zfs/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/snapbuilder/build.go
  pkg/builder/snapbuilder/buildlist.go
  pkg/builder/snapbuilder/kubernetes.go
  pkg/builder/snapbuilder/snapshot.go
  pkg/builder/volbuilder/build.go
  pkg/builder/volbuilder/buildlist.go
  pkg/builder/volbuilder/kubernetes.go
  pkg/builder/volbuilder/volume.go
  pkg/driver/agent.go
  pkg/generated/clientset/internalclientset/clientset.go
  pkg/generated/clientset/internalclientset/fake/clientset_generated.go
  pkg/generated/clientset/internalclientset/fake/register.go
  pkg/generated/clientset/internalclientset/scheme/register.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/doc.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/doc.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfs_client.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfssnapshot.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfsvolume.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/generated_expansion.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfs_client.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfssnapshot.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfsvolume.go
  pkg/generated/informer/externalversions/factory.go
  pkg/generated/informer/externalversions/generic.go
  pkg/generated/informer/externalversions/zfs/interface.go
  pkg/generated/informer/externalversions/zfs/v1alpha1/interface.go
  pkg/generated/informer/externalversions/zfs/v1alpha1/zfssnapshot.go
  pkg/generated/informer/externalversions/zfs/v1alpha1/zfsvolume.go
  pkg/generated/lister/zfs/v1alpha1/expansion_generated.go
  pkg/generated/lister/zfs/v1alpha1/zfssnapshot.go
  pkg/generated/lister/zfs/v1alpha1/zfsvolume.go
  pkg/mgmt/snapshot/builder.go
  pkg/mgmt/snapshot/snapshot.go
  pkg/mgmt/volume/builder.go
  pkg/mgmt/volume/volume.go
  pkg/zfs/mount.go
  pkg/zfs/resize.go
  pkg/zfs/volume.go
  pkg/zfs/zfs_util.go
  tests/utils.go
Labels: documentation, enhancement
