Repository openebs/zfs-localpv, pull requests merged in 2020-07, with the labels that each got.

#164 feat(shared): adding shared mount support ZFSPV volumes
  changelogs/unreleased/164-pawanpraka1
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/zfssnapshot-crd.yaml
  deploy/yamls/zfsvolume-crd.yaml
  deploy/zfs-operator.yaml
  pkg/apis/openebs.io/zfs/v1/zfsvolume.go
  pkg/builder/volbuilder/build.go
  pkg/driver/controller.go
  pkg/driver/grpc.go
  pkg/zfs/mount.go
Labels: enhancement

#170 feat(btrfs): adding support to have btrfs filesystem for ZFS-LocalPV
  buildscripts/zfs-driver/Dockerfile
  changelogs/unreleased/170-pawanpraka1
Labels: enhancement

#171 feat(zfspv): check pod-status in BDD test
  changelogs/unreleased/171-vaniisgh
  ci/ci-test.sh
Labels: enhancement, project/community

#172 fix(btrfs): fixing duplicate UUID issue with btrfs
  changelogs/172-pawanpraka1
  pkg/zfs/btrfs_util.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: bug

#175 feat(zfspv) Add golint check to travis
  .travis.yml
  Makefile
  changelogs/unreleased/175-vaniisgh
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/zfssnapshot-crd.yaml
  deploy/yamls/zfsvolume-crd.yaml
  deploy/zfs-operator.yaml
  pkg/apis/openebs.io/zfs/v1/zfssnapshot.go
  pkg/apis/openebs.io/zfs/v1/zfsvolume.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfssnapshot.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
  pkg/client/k8s/v1alpha1/clientset.go
  pkg/client/k8s/v1alpha1/configmap.go
  pkg/client/k8s/v1alpha1/configmap_test.go
  pkg/client/k8s/v1alpha1/dynamic.go
  pkg/client/k8s/v1alpha1/dynamic_test.go
  pkg/client/k8s/v1alpha1/namespace.go
  pkg/client/k8s/v1alpha1/node.go
  pkg/client/k8s/v1alpha1/resource.go
  pkg/client/k8s/v1alpha1/resource_test.go
  pkg/common/helpers/helpers.go
  pkg/usage/const.go
  pkg/usage/versionset.go
  pkg/zfs/btrfs_util.go
  pkg/zfs/mount.go
  pkg/zfs/xfs_util.go
  pkg/zfs/zfs_util.go
  tests/pod/buildlist.go
  tests/pod/pod.go
  tests/pvc/buildlist.go
  tests/pvc/persistentvolumeclaim.go
  tests/sc/buildlist.go
  tests/utils.go
Labels: enhancement, project/community

#174 feat(bdd): adding snapshot and clone releated test cases
  .travis.yml
  changelogs/unreleased/172-pawanpraka1
  changelogs/unreleased/174-pawanpraka1
  ci/ci-test.sh
  deploy/sample/zfssnapclass.yaml
  tests/provision_test.go
  tests/run_test.go
  tests/suite_test.go
  tests/utils.go
Labels: enhancement

#176 chore(doc): adding btrfs filesystem in the doc
  README.md
  docs/resize.md
Labels: documentation

#179 fix(zfspv): fixing mounting issue with xfs on centos
  buildscripts/zfs-driver/Dockerfile
  changelogs/unreleased/179-pawanpraka1
Labels: bug

#180 fix(zfspv): fixing mounting issue with xfs on centos
  buildscripts/zfs-driver/Dockerfile
  changelogs/unreleased/179-pawanpraka1
Labels: bug

#181 chore(readme): updating the readme for application-consistent snapshot
  README.md
Labels: documentation

#177 chore(changelog): adding v0.9.0 changelog in the repo
  CHANGELOG.md
  changelogs/released/v0.9.0-RC1/160-vaniisgh
  changelogs/released/v0.9.0-RC1/161-vaniisgh
  changelogs/released/v0.9.0-RC1/164-pawanpraka1
  changelogs/released/v0.9.0-RC1/166-vaniisgh
  changelogs/released/v0.9.0-RC1/167-vaniisgh
  changelogs/released/v0.9.0-RC1/170-pawanpraka1
  changelogs/released/v0.9.0-RC1/171-vaniisgh
  changelogs/released/v0.9.0-RC1/172-pawanpraka1
  changelogs/released/v0.9.0-RC1/174-pawanpraka1
  changelogs/released/v0.9.0-RC1/175-vaniisgh
  changelogs/released/v0.9.0-RC2/179-pawanpraka1
Labels: documentation

#184 fix(zfspv): mounting the volume if it is ready
  changelogs/unreleased/184-pawanpraka1
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: enhancement

#183 fix(xfs, uuid): fixed uuid generation issue when mount fails
  changelogs/unreleased/183-pawanpraka1
  pkg/zfs/xfs_util.go
Labels: bug

#186 fix(yaml): removing volumeLifecycleModes from the operator yaml
  changelogs/unreleased/186-pawanpraka1
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: bug

#190 docs ( readme ) Update Readme to specify usage of child dataset for poolname
  README.md
Labels: documentation
