Repository openebs/zfs-localpv, pull requests merged in 2020-04, with the labels that each got.

#73 feat(crd): upgrade script for refactoring the CRD
  upgrade/cleanup.sh
  upgrade/crd.yaml
  upgrade/upgrade.sh
Labels: enhancement

#75 feat(crd-gen): automate the CRDs generation with validations for APIs
  Makefile
  buildscripts/update-crd.sh
  deploy/yamls/zfs.openebs.io_zfssnapshots.yaml
  deploy/yamls/zfs.openebs.io_zfsvolumes.yaml
  pkg/apis/openebs.io/zfs/v1alpha1/doc.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfssnapshot.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
  pkg/builder/snapbuilder/kubernetes.go
  pkg/builder/volbuilder/kubernetes.go
  pkg/generated/clientset/internalclientset/clientset.go
  pkg/generated/clientset/internalclientset/fake/clientset_generated.go
  pkg/generated/clientset/internalclientset/fake/register.go
  pkg/generated/clientset/internalclientset/scheme/register.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfs_client.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfssnapshot.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/fake/fake_zfsvolume.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfs_client.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfssnapshot.go
  pkg/generated/clientset/internalclientset/typed/zfs/v1alpha1/zfsvolume.go
  pkg/generated/informer/externalversions/factory.go
  pkg/generated/informer/externalversions/generic.go
  pkg/generated/informer/externalversions/zfs/interface.go
  pkg/generated/informer/externalversions/zfs/v1alpha1/zfssnapshot.go
  pkg/generated/informer/externalversions/zfs/v1alpha1/zfsvolume.go
  pkg/mgmt/snapshot/builder.go
  pkg/mgmt/volume/builder.go
Labels: enhancement

#76 feat(zfspv): handling unmounted volume .
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: enhancement

#78 feat(zfspv): handling unmounted volume
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: enhancement

#80 feat(zfspv): adding poolname info to the PV volumeattributes
  pkg/driver/controller.go
  pkg/zfs/volume.go
Labels: enhancement

#77 chore(changelog): adding v0.6-RC1 changelog
  CHANGELOG.md
Labels: documentation, pr/hold-merge

#81 feat(yaml): adding 0.6.0 tag to the v0.6.x deployment yaml
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#89 fix(zfspv): fixing data loss in case of pod deletion
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: bug

#90 fix(zfspv): fixing data loss in case of pod deletion
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: bug

#91 fix(zfspv): fixing data loss in case of pod deletion
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: bug

#96 feat(yaml): update the v0.6.x yaml to the latest 0.6.1 tag
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#95 feat(yaml): update the v0.4.x yaml to the latest 0.4.1 tag
  deploy/zfs-operator.yaml
Labels: enhancement

#92 added developer environment examples
  docs/developer-setup-examples.md
Labels: community

#85 feat(attach): avoid creation of volumeattachment object
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
  upgrade/README.md
  upgrade/cleanup.sh
  upgrade/upgrade.sh
Labels: bug, pr/release-note

#99 docs(project): adding project specific files
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  RELEASE.md
Labels: documentation

#94 feat(topology): adding support for custom topology keys
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
  docs/faq.md
  pkg/client/k8s/v1alpha1/node.go
  pkg/driver/agent.go
  pkg/driver/scheduler.go
  unreleased/94-pawanpraka1
Labels: community, enhancement, pr/release-note

#101 fix(topokey): changing topology key to unique name
  pkg/zfs/volume.go
  unreleased/101-pawanpraka1
Labels: bug, community
