Repository openebs/zfs-localpv, pull requests merged in 2020-11, with the labels that each got.

#230 feat(upgrade): support parallel/faster upgrades for node daemonset
  changelogs/unreleased/230-pawanpraka1
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#234 feat(clone): add support for creating the Clone from volume as datasource
  changelogs/unreleased/234-pawanpraka1
  pkg/driver/controller.go
  pkg/zfs/volume.go
  pkg/zfs/zfs_util.go
Labels: feature

#237 chore(yaml): changing the zfs-driver images to multi-arch docker hub images
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: bug

#243 fix(kust): rename the kustomize.yaml file to kustomization.yaml
  deploy/yamls/kustomization.yaml
Labels: bug

#241 chore(doc): adding v1.1.0 changelog
  CHANGELOG.md
  changelogs/released/v1.1.0-RC1/225-codegagan
  changelogs/released/v1.1.0-RC1/230-pawanpraka1
  changelogs/released/v1.1.0-RC1/231-pawanpraka1
  changelogs/released/v1.1.0-RC1/233-prateekpandey14
  changelogs/released/v1.1.0-RC1/234-pawanpraka1
  changelogs/released/v1.1.0/237-w3aman
Labels: documentation

#242 chore(yaml): updating the 1.1.x branch yaml with the release images
  deploy/yamls/kustomization.yaml
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#244 chore(refactor): move btrfs code out of zfs package
  pkg/btrfs/btrfs_util.go
  pkg/zfs/zfs_util.go
Labels: refactoring
