Repository openebs/zfs-localpv, pull requests merged in 2020-12, with the labels that each got.

#245 chore(refactor): move xfs and mount code out of zfs package
  pkg/driver/agent.go
  pkg/mount/mount_utils.go
  pkg/xfs/xfs_util.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: refactoring

#246 chore(doc): update restore doc with node mapping details
  docs/backup-restore.md
Labels: documentation

#249 chore(refactor): refactor scheduler for ZFS-LocalPV
  pkg/driver/controller.go
  pkg/driver/schd_helper.go
  pkg/scheduler/scheduler.go
Labels: refactoring

#253 fix(doc): fixed the kustomization yaml file path in readme
  README.md
Labels: documentation

#255 feat(image): moving to ubuntu bionic(18.04 LTS) docker image
  buildscripts/zfs-driver/Dockerfile
Labels: bug

#256 fix(sanity): fixing flaky sanity test case
  buildscripts/zfs-driver/zfs-driver.Dockerfile
  ci/sanity.sh
  pkg/driver/controller.go
Labels: bug

#251 chore(doc): adding installation instruction for microk8s
  README.md
Labels: documentation

#254 refactor(readme): refactoring readme
  README.md
  docs/clone.md
  docs/snapshot.md
Labels: documentation

#258 chore(yaml): updating 1.2.x branch with the image tag
  deploy/yamls/kustomization.yaml
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: documentation, enhancement

#261 chore(yaml): updating 1.2.x branch with the 1.2.1 image tag
  deploy/yamls/kustomization.yaml
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#257 chore(doc): adding 1.2.0 changelog
  CHANGELOG.md
  changelogs/released/v1.2.0-RC1/232-pawanpraka1
  changelogs/released/v1.2.0-RC1/243-pawanpraka1
  changelogs/released/v1.2.0-RC1/244-pawanpraka1
  changelogs/released/v1.2.0-RC1/245-pawanpraka1
  changelogs/released/v1.2.0-RC1/248-pawanpraka1
  changelogs/released/v1.2.0-RC1/249-pawanpraka1
  changelogs/released/v1.2.0-RC1/250-shubham14bajpai
  changelogs/released/v1.2.0-RC1/255-pawanpraka1
  changelogs/released/v1.2.0-RC1/256-pawanpraka1
  changelogs/released/v1.2.1/260-pawanpraka1
Labels: documentation

#263 refact(csi): use common lib-csi imports
  go.mod
  go.sum
  pkg/builder/bkpbuilder/build.go
  pkg/builder/bkpbuilder/kubernetes.go
  pkg/builder/restorebuilder/build.go
  pkg/builder/restorebuilder/kubernetes.go
  pkg/builder/snapbuilder/build.go
  pkg/builder/snapbuilder/kubernetes.go
  pkg/builder/volbuilder/build.go
  pkg/builder/volbuilder/kubernetes.go
  pkg/client/k8s/v1alpha1/clientset_test.go
  pkg/client/k8s/v1alpha1/config_test.go
  pkg/client/k8s/v1alpha1/configmap_test.go
  pkg/client/k8s/v1alpha1/k8s.go
  pkg/client/k8s/v1alpha1/resource_test.go
  pkg/common/kubernetes/client/client_test.go
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/usage/ping.go
  pkg/usage/usage.go
  pkg/usage/versionset.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
  tests/container/container.go
  tests/deploy/deployment.go
  tests/deploy/kubernetes.go
  tests/k8svolume/build.go
  tests/pod/build.go
  tests/pod/kubernetes.go
  tests/pts/pts.go
  tests/pvc/build.go
  tests/pvc/buildlist.go
  tests/pvc/kubernetes.go
  tests/sc/build.go
  tests/sc/buildlist.go
  tests/sc/kubernetes.go
  vendor/github.com/openebs/lib-csi/LICENSE
  vendor/github.com/openebs/lib-csi/pkg/btrfs/btrfs_util.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/clientset.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/config.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/configmap.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/dynamic.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/k8s.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/namespace.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/node.go
  vendor/github.com/openebs/lib-csi/pkg/client/k8s/resource.go
  vendor/github.com/openebs/lib-csi/pkg/common/env/env.go
  vendor/github.com/openebs/lib-csi/pkg/common/errors/errors.go
  vendor/github.com/openebs/lib-csi/pkg/common/errors/types.go
  vendor/github.com/openebs/lib-csi/pkg/common/helpers/helpers.go
  vendor/github.com/openebs/lib-csi/pkg/common/kubernetes/client/client.go
  vendor/github.com/openebs/lib-csi/pkg/mount/mount_utils.go
  vendor/github.com/openebs/lib-csi/pkg/scheduler/scheduler.go
  vendor/github.com/openebs/lib-csi/pkg/xfs/xfs_util.go
  vendor/modules.txt
Labels: enhancement

#264 Cross Build enviroment bug fixes
  buildscripts/build.sh
  pkg/driver/agent.go
Labels: bug

#262 fix(mount): creating directory with 0755 permission
  pkg/zfs/mount.go
Labels: bug
