Repository openebs/zfs-localpv, pull requests merged in 2020-06, with the labels that each got.

#146 chore(changelog): add missing changelog for v0.8 release
  changelogs/unreleased/122-w3aman
  changelogs/unreleased/124-pawanpraka1
  changelogs/unreleased/128-pawanpraka1
  changelogs/unreleased/137-pawanpraka1
  changelogs/unreleased/138-Icedroid
Labels: documentation

#145 fix(pvc): fixing stale ZFSVolume CR issue when deleting pending PVC
  changelogs/unreleased/145-pawanpraka1
  pkg/driver/controller.go
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: bug

#149 feat(centos): adding operator yaml for centos7 and centos8
  buildscripts/generate-manifests.sh
  changelogs/unreleased/149-pawanpraka1
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
Labels: enhancement

#150 feat(usage): include pvc name in volume events
  changelogs/unreleased/150-pawanpraka1
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
  deploy/zfs-operator.yaml
  pkg/driver/controller.go
  pkg/usage/googleanalytics.go
  pkg/usage/usage.go
Labels: enhancement

#151 feat(mount): moving to legacy mount
  changelogs/unreleased/151-pawanpraka1
  pkg/zfs/mount.go
  pkg/zfs/zfs_util.go
Labels: enhancement

#153 adding missing changelog from the contributer
  changelogs/unreleased/133-Icedroid
Labels: documentation

#155 chore(changelog): adding 0.8.0 changelogs
  CHANGELOG.md
  changelogs/released/0.8.0-RC1/121-pawanpraka1
  changelogs/released/0.8.0-RC1/122-w3aman
  changelogs/released/0.8.0-RC1/124-pawanpraka1
  changelogs/released/0.8.0-RC1/128-pawanpraka1
  changelogs/released/0.8.0-RC1/133-Icedroid
  changelogs/released/0.8.0-RC1/137-pawanpraka1
  changelogs/released/0.8.0-RC1/138-Icedroid
  changelogs/released/0.8.0-RC1/140-pawanpraka1
  changelogs/released/0.8.0-RC1/144-cruwe
  changelogs/released/0.8.0-RC1/145-pawanpraka1
  changelogs/released/0.8.0-RC1/149-pawanpraka1
  changelogs/released/0.8.0-RC1/150-pawanpraka1
  changelogs/released/0.8.0-RC1/151-pawanpraka1
Labels: documentation

#154 feat(yaml): updating v0.8.0 operator yaml to use 0.8.0 image tag
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: documentation

#156 chore(changelog): fixing link in the changelog
  CHANGELOG.md
Labels: documentation

#157 feat(yaml): updating v0.8.0 operator yaml to use 0.8.0 image tag
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#158 feat(yaml): updating master operator yaml to use ci image tag
  deploy/operators/centos7/zfs-operator.yaml
  deploy/operators/centos8/zfs-operator.yaml
  deploy/yamls/centos7/zfs-driver.yaml
  deploy/yamls/centos8/zfs-driver.yaml
  deploy/yamls/ubuntu/zfs-driver.yaml
  deploy/zfs-operator.yaml
Labels: enhancement

#161 feat(zfspv): filter grpc logs to reduce the pollution
  changelogs/unreleased/161-vaniisgh
  pkg/driver/grpc.go
Labels: feature, project/community

#160 chore(doc): Update docs for Gomodule support
  Gopkg.lock
  Gopkg.toml
  buildscripts/build.sh
  changelogs/unreleased/160-vaniisgh
  docs/developer-setup-examples.md
  docs/developer-setup.md
Labels: documentation, project/community

#166 feat(zfspv): move to klog
  changelogs/unreleased/166-vaniisgh
  cmd/main.go
  go.mod
  go.sum
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/scheduler.go
  pkg/mgmt/snapshot/builder.go
  pkg/mgmt/snapshot/snapshot.go
  pkg/mgmt/snapshot/start.go
  pkg/mgmt/volume/builder.go
  pkg/mgmt/volume/start.go
  pkg/mgmt/volume/volume.go
  pkg/version/version.go
  pkg/zfs/mount.go
  pkg/zfs/resize.go
  pkg/zfs/volume.go
  pkg/zfs/xfs_util.go
  pkg/zfs/zfs_util.go
  tests/suite_test.go
  vendor/github.com/Sirupsen/logrus/.gitignore
  vendor/github.com/Sirupsen/logrus/.travis.yml
  vendor/github.com/Sirupsen/logrus/CHANGELOG.md
  vendor/github.com/Sirupsen/logrus/LICENSE
  vendor/github.com/Sirupsen/logrus/README.md
  vendor/github.com/Sirupsen/logrus/alt_exit.go
  vendor/github.com/Sirupsen/logrus/appveyor.yml
  vendor/github.com/Sirupsen/logrus/doc.go
  vendor/github.com/Sirupsen/logrus/entry.go
  vendor/github.com/Sirupsen/logrus/exported.go
  vendor/github.com/Sirupsen/logrus/formatter.go
  vendor/github.com/Sirupsen/logrus/go.mod
  vendor/github.com/Sirupsen/logrus/go.sum
  vendor/github.com/Sirupsen/logrus/hooks.go
  vendor/github.com/Sirupsen/logrus/json_formatter.go
  vendor/github.com/Sirupsen/logrus/logger.go
  vendor/github.com/Sirupsen/logrus/logrus.go
  vendor/github.com/Sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/Sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/Sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/Sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/Sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/Sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/Sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/Sirupsen/logrus/text_formatter.go
  vendor/github.com/Sirupsen/logrus/writer.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/modules.txt
Labels: enhancement, project/community

#167 feat(zfspv) add go lint target
  Makefile
  changelogs/unreleased/167-vaniisgh
Labels: enhancement
