Repository openebs/zfs-localpv, pull requests merged in 2021-04, with the labels that each got.

#301 chore(yaml): fixing autogen yaml description
  deploy/yamls/zfsbackup-crd.yaml
  deploy/yamls/zfsrestore-crd.yaml
  deploy/yamls/zfssnapshot-crd.yaml
  deploy/yamls/zfsvolume-crd.yaml
  deploy/zfs-operator.yaml
Labels: documentation

#303 feat(zfspv): remove finalizer that is owned by ZFS-LocalPV
  pkg/mgmt/snapshot/snapshot.go
  pkg/mgmt/volume/volume.go
  pkg/zfs/mount.go
  pkg/zfs/volume.go
Labels: enhancement

#307 docs(localpv): Add note about k0s use of custom kubelet directory
  README.md
Labels: project/community

#313 chore(doc): update the import-existing-volume doc with finalizer info
  docs/import-existing-volume.md
Labels: documentation
