Repository openebs/zfs-localpv, pull requests merged in 2021-01, with the labels that each got.

#271 chore(operator): bump k8s csi to latest stable container images
  README.md
  deploy/sample/zfssnapclass.yaml
  deploy/sample/zfssnapshot.yaml
  deploy/yamls/zfs-driver.yaml
  deploy/zfs-operator.yaml
  tests/run_test.go
Labels: enhancement

#266 feat(schd): adding capacity weighted scheduler
  changelogs/unreleased/266-pawanpraka1
  pkg/driver/schd_helper.go
Labels: enhancement

#247 feat(chart): add helm chart for zfs local pv
  .github/workflows/release.yml
  deploy/helm/charts/.helmignore
  deploy/helm/charts/Chart.yaml
  deploy/helm/charts/README.md
  deploy/helm/charts/crds/volumesnapshotclasses.yaml
  deploy/helm/charts/crds/volumesnapshotcontents.yaml
  deploy/helm/charts/crds/volumesnapshots.yaml
  deploy/helm/charts/crds/zfsbackup.yaml
  deploy/helm/charts/crds/zfsrestore.yaml
  deploy/helm/charts/crds/zfssnapshot.yaml
  deploy/helm/charts/crds/zfsvolume.yaml
  deploy/helm/charts/templates/NOTES.txt
  deploy/helm/charts/templates/_helpers.tpl
  deploy/helm/charts/templates/configmap.yaml
  deploy/helm/charts/templates/csidriver.yaml
  deploy/helm/charts/templates/rbac.yaml
  deploy/helm/charts/templates/zfs-contoller.yaml
  deploy/helm/charts/templates/zfs-node.yaml
  deploy/helm/charts/values.yaml
Labels: feature

#274 chore(changelog): adding v1.3.0 changelog
  CHANGELOG.md
  changelogs/released/v1.3.0/262-pawanpraka1
  changelogs/released/v1.3.0/263-shubham14bajpai
  changelogs/released/v1.3.0/264-praveengt
  changelogs/released/v1.3.0/266-pawanpraka1
  changelogs/released/v1.3.0/271-shubham14bajpai
Labels: documentation
