Repository openebs/zfs-localpv, pull requests merged in 2021-05, with the labels that each got.

#304 feat(migration): adding support to migrate the PV to a new node
  changelogs/304-pawanpraka1
  cmd/main.go
  deploy/yamls/zfs-driver.yaml
  deploy/yamls/zfsvolume-crd.yaml
  deploy/zfs-operator.yaml
  docs/faq.md
  pkg/apis/openebs.io/zfs/v1/zfsvolume.go
  pkg/builder/volbuilder/build.go
  pkg/config/config.go
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/zfs/volume.go
Labels: feature

#320 fix(topo): support old topology key for backward compatibility
  changelogs/unreleased/304-pawanpraka1
  changelogs/unreleased/320-pawanpraka1
  pkg/driver/agent.go
  pkg/zfs/volume.go
Labels: bug

#321 (bugbash) refact(zfspv) Removes unused import, variables and functions.
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/grpc.go
  pkg/zfs/volume.go
  pkg/zfs/zfs_util.go
  tests/suite_test.go
Labels: project/community

#324 Fix deadcode and shebangs error
  buildscripts/test-cov.sh
  ci/ci-test.sh
  pkg/driver/grpc.go
Labels: event/kubecon-eu21-bugbash

#330 feat(action): autogenerate the operator yaml with the image tag
  .github/workflows/release.yml
Labels: feature
