Repository openebs/zfs-localpv, pull requests merged in 2021-06, with the labels that each got.

#325 Change file permissions to fix gosec G301 Error
  pkg/zfs/mount.go
Labels: event/kubecon-eu21-bugbash

#349 fix(actions): skip release workflow on helm release
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: enhancement

#348 Fix bunch of typos
  deploy/helm/charts/Chart.yaml
  deploy/helm/charts/crds/volumesnapshots.yaml
  deploy/helm/charts/crds/zfssnapshot.yaml
  deploy/helm/charts/values.yaml
  deploy/yamls/zfs-driver.yaml
  deploy/yamls/zfssnapshot-crd.yaml
  deploy/zfs-operator.yaml
  pkg/apis/openebs.io/zfs/v1/zfssnapshot.go
  pkg/apis/openebs.io/zfs/v1alpha1/zfssnapshot.go
Labels: documentation

#353 fix(crash): reuse the err variable
  pkg/driver/controller.go
Labels: bug

#352 fix(chart): remove zfsNode.podLabels.name from values
  deploy/helm/charts/Chart.yaml
  deploy/helm/charts/values.yaml
Labels: enhancement
